version: '3'
services:
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: 'false'
    volumes:
      - ./cms:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - mysql

  mysql:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi

  home:
    image: node:14.15-alpine
    volumes:
      - ./home:/srv/app
    ports:
      - 80:3000
    working_dir: /srv/app
    entrypoint: ["npm", "start"]

  blogs:
    image: node:14.15-alpine
    volumes:
      - ./blogs:/srv/app
    ports:
      - 3010:3000
    working_dir: /srv/app
    entrypoint: ["npm", "run", "dev"]

  notes:
    image: node:14.15-alpine
    volumes:
      - ./notes:/srv/app
    ports:
      - 3020:3000
    working_dir: /srv/app
    entrypoint: ["npm", "run", "dev"]

  photos:
    image: node:14.15-alpine
    volumes:
      - ./photos:/srv/app
    ports:
      - 3030:3000
    working_dir: /srv/app
    entrypoint: ["npm", "run", "dev"]